name: CI

on: [push]

jobs:
  test-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: cleanup docker cache
        run: |
          docker system prune -af --volumes || true
      - name: run containers
        run: |
          docker compose down --remove-orphans || true
          docker compose up -d --build