name: CI

on: [push]

jobs:
  test-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: cleanup docker cache
        run: |
          docker system prune -af || true
      - name: run containers
        run: |
          docker compose -f docker-compose.yml -f docker-compose.prod.yml down --remove-orphans || true
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
      - name: wait for backend
        run: |
          until curl -fsS http://127.0.0.1:8000/api/v1/healthchecks/ >/dev/null; do sleep 2; done
      - name: wait for frontend
        run: |
          until curl -fsS http://127.0.0.1:8100/ >/dev/null; do sleep 2; done