{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "book-club.fullname" . }}-vault-secret
  labels:
    {{- include "book-club.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: secret
  path: {{ .Values.vault.secretPath }}
  destination:
    name: book-club-secrets
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ include "book-club.fullname" . }}-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ include "book-club.fullname" . }}-vault-auth
  labels:
    {{- include "book-club.labels" . | nindent 4 }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: {{ .Values.vault.role }}
    serviceAccount: default
{{- end }}
